### ISSUE TITLE
Unclear how to install this

### ISSUE THREAD

**Issue by KirilOkun** [peterfajdiga/kwin4_effect_geometry_change#10]
Just installed Polonium window manager and it suggests this effect but i can't find anywhere how to actually install it. I downloaded the tar.gz but neither Desktop0 Effects nor KWin Scripts settings can install it.

**Comment by peterfajdiga** [comment]
If you're running Plasma 5, try version [1.1](https://github.com/peterfajdiga/kwin4_effect_geometry_change/releases/tag/v1.1) of this effect.

I've added notes to the newer versions stating that they're incompatible with Plasma 5.

**Comment by KirilOkun** [comment]
I'm on Plasma v 6.0.4

**Comment by peterfajdiga** [comment]
There are a few different ways you can install a desktop effect:
- extract the contents of the package folder from the tar.gz into ~/.local/share/kwin/effects/kwin4_effect_geometry_change,
- open the Desktop Effects settings, click on "Get New Desktop Effects", find the "Geometry Change" effect, and install it, or
- clone this repo and run `make install`.

**Comment by zastrixarundell** [comment]
I  had this installed via KDE and the software store but it didn't want to work. Here's how I fixed it @KirilOkun:

* Disable it if it's enabled on desktop effect
* Delete the folder `rm -rf ~/.local/share/kwin/effects/kwin4_effect_geometry_change`
* Reinstall it via store
* Enable it (Apply), Disable it (Apply), Enable it (Apply)

**Comment by tockudex** [comment]
> There are a few different ways you can install a desktop effect:
> 
>     * extract the contents of the package folder from the tar.gz into ~/.local/share/kwin/effects/kwin4_effect_geometry_change,
> 
>     * open the Desktop Effects settings, click on "Get New Desktop Effects", find the "Geometry Change" effect, and install it, or
> 
>     * clone this repo and run `make install`.

Hey,
Hate to necrobump, but I wondered if you could add this information to the README, for clarity?

**Comment by peterfajdiga** [comment]
Good idea, done.
