### ISSUE TITLE
Missing animation when dragging from maximized mode

### ISSUE THREAD

**Issue by AlphaCraft9658** [peterfajdiga/kwin4_effect_geometry_change#12]
All the animations work very well, except if I want to drag a maximized window, which then changes its size. It just pops into its new size. I am currently trying out Plasma 6 with Wayland.

**Comment by peterfajdiga** [comment]
Thanks for the report. This happens because the animation is disabled for dragged moves and resizes to prevent the window lagging behind the cursor.
