### ISSUE TITLE
Window gets incorrectly placed for one frame when un-snapping it through Meta+LMB

### ISSUE THREAD

**Issue by im-tem** [peterfajdiga/kwin4_effect_geometry_change#2]
Honestly, I don't know what is to blame in this situation (effect or how kwin handles un-snapping) but it only happens when using Meta+LMB. Sorry if this behavior is not the fault of this project...

https://user-images.githubusercontent.com/18075164/235340824-5b021a72-069a-42b1-a8bd-1e401cc647e0.mp4

(X11 session, KDE 5.27.4)

**Comment by peterfajdiga** [comment]
Hi, thanks for the report. I can reproduce it even with the effect disabled, so it may be a KWin issue.

The easiest way I found to reproduce it (with or without the script enabled) is this:
1. Place a window at the center of the screen
2. Snap the window to the left edge
3. Press Meta+LMB on the snapped window without moving the mouse. The window un-snaps to the center of the screen - where it was before snapping.
4. Move the mouse slightly. The window suddenly moves to the left edge.

Can you confirm this happens even with the script disabled and that this is the same issue you reported?

**Comment by im-tem** [comment]
You're correct! This indeed happens and also seems to be related to the issue

**Comment by peterfajdiga** [comment]
Thank you!
