### ISSUE TITLE
Ignores blur during the animation

### ISSUE THREAD

**Issue by zastrixarundell** [peterfajdiga/kwin4_effect_geometry_change#5]
Hi, great plugin! The only issue I have which makes me not want to use it is that blur is lost when using it.

https://github.com/peterfajdiga/kwin4_effect_geometry_change/assets/30195425/3b2e9f46-26ab-45c4-918e-f4938e617719

**Comment by peterfajdiga** [comment]
Hi, thanks for the report! I've fixed it by setting `WindowForceBlurRole` to true for the duration of the animation.

**Comment by zastrixarundell** [comment]
Thanks, it's working perfect now!

**Comment by CT-66** [comment]
Where do you add this? Any config file?

**Comment by peterfajdiga** [comment]
@CT-66 This is not part of a config. This has been fixed in the code. The fix is contained in versions 1.1 and newer.
