### ISSUE TITLE
Broken un-maximizing animation

### ISSUE THREAD

**Issue by AlphaCraft9658** [peterfajdiga/kwin4_effect_geometry_change#8]
Every time the un-maxinizing animation is played, it starts playing as if the window spanned the entirety of my two screens. An additional artifact is that there are some glitchy remains on the second screen, which only disappear if a window or anything below it updates. Additionally, near the end of that animation, blurring effects are very shortly broken, until the animation is finished. Unfortunately, I cannot attach a video at this moment, but will try to do so tomorrow if needed.

**Comment by peterfajdiga** [comment]
Thanks for the report! Do you have any other maximize effects enabled? For example the built-in _Maximize_ effect?

**Comment by AlphaCraft9658** [comment]
> Thanks for the report! Do you have any other maximize effects enabled? For example the built-in _Maximize_ effect?

I think the built-in effect is enabled. But is the un-maximizing also part of that?

**Comment by peterfajdiga** [comment]
Yes, the built-in _Maximize_ effect provides both the maximize and un-maximize animations.

**Comment by AlphaCraft9658** [comment]
> Yes, the built-in _Maximize_ effect provides both the maximize and un-maximize animations.

Yeah, I checked previously and found out. Forgot to tell you. I don't exactly know why rn, but something still feels a bit wonky about this effect. I do remember it's a pretty minor detail though.
