### ISSUE TITLE
Request: Exclude Window Shade

### ISSUE THREAD

**Issue by AndydeCleyre** [peterfajdiga/kwin4_effect_geometry_change#9]
Hello, and thanks for this!

I really like how this appears for most window actions, but mostly the window packing action (maybe renamed these days).

But when I shade and unshade windows, the title bar wiggles, flickers, and I momentarily get the title text and titlebar controls stretched far down the window height, which does not look good IMO.

So I request that the window shade action be excluded from the animation provided by this effect.

https://github.com/peterfajdiga/kwin4_effect_geometry_change/assets/1787385/2faf573d-d3ba-4dc7-8a9a-b87bc55cfcdb

**Comment by peterfajdiga** [comment]
Hi, thanks for the report. This is just how Kwin's scaling animation works, though. It also happens when resizing between a small and a large window size. I think that making exceptions for certain resizings (or for shading) would be even more jarring due to inconsistency.
